### ISSUE TITLE
"Falsehoods about REST APIs" is now a dead link

### ISSUE THREAD

**Issue by kevinlul** [kdeldycke/awesome-falsehood#101]
#### Preliminary checks

* [x] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/code-of-conduct.md)
* [x] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/contributing.md)
* [x] I have checked there is not other [Issues](https://github.com/kdeldycke/awesome-falsehood/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-falsehood/pulls) covering the same topic to open

#### Summary

While the domain remains live, it appears the hosting platform, WebFaction, was shut off as of September 15.

**Comment by kdeldycke** [comment]
Thanks for the hint! Just  fixed it upstream in 73f7fc3.
