### ISSUE TITLE
Falsehoods About Plain Text

### ISSUE THREAD

**Issue by Hussell** [kdeldycke/awesome-falsehood#107]
I believe this would fit well in the Internationalization section. I'm the author, but this is my first and only attempt at promoting it. It doesn't seem to have gotten much attention so far.

https://jeremyhussell.blogspot.com/2017/11/falsehoods-programmers-believe-about.html#main

Falsehoods about Plain Text - Writing systems around the world and why it's surprising Unicode works as well as it does.

**Comment by Hussell** [comment]
"Plain text can't cut it and reasons why Unicode works as well as it does."

I think removing "it's surprising" has substantially changed the meaning.

**Comment by kdeldycke** [comment]
> I think removing "it's surprising" has substantially changed the meaning.

Fixed in https://github.com/kdeldycke/awesome-falsehood/commit/b206722f1a75c09c8922f775d5cc61ede098c258.
