### ISSUE TITLE
Add family falsehoods

### ISSUE THREAD

**Issue by ZevEisenberg** [kdeldycke/awesome-falsehood#15]
Maybe these should be turned into a proper list first, so you can link to that, but there's some good fodder for a new "falsehoods" list here: https://twitter.com/edent/status/846270908138426369 (via @jaredsinclair)

**Comment by kdeldycke** [comment]
The author, @edent, made an article out of his tweet storm at: https://shkspr.mobi/blog/2017/03/falsehoods-programmers-believe-about-families/ . That link is more appropriate.

This article was discussed as well on HN: https://news.ycombinator.com/item?id=13985261

**Comment by edent** [comment]
Haha! Thanks - saves me from having to add it myself ☺️
