### ISSUE TITLE
Do we need to add something about "a place, such as a city, being in one time zone"?

### ISSUE THREAD

**Issue by revk** [kdeldycke/awesome-falsehood#155]
### URL of the article or project

https://www.aljazeera.com/news/2023/3/26/lebanon-awakes-to-two-times-of-day-amid-daylight-savings-dispute

### Motivation

Seems there are places with more than one time zone in operation at the same, err, time.

### Affiliation

- [ ] I am the author of the article or project
- [ ] I am working for/with the company which is publishing the article or project
- [X] I'm just a rando who stumbled upon this via social networks

### Self checks

- [ ] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/code-of-conduct.md)

- [ ] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/contributing.md)

- [X] I have checked there is no other [Issues](https://github.com/kdeldycke/awesome-falsehood/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-falsehood/pulls) covering the same topic to open

**Comment by davidsneighbour** [comment]
If we have the awesome falsehood that a group of people in Germany believes that Germany never surrendered after World War 2 and is still what they call "the Weimar Republic" and not the first divided, then united Germany, then yes, the daylight savings time conflict should be included. 

If a sectarian group's opinion (doctrine?) (the Maronite Church) is not an official set system, then where is the falsehood here?

**Comment by kdeldycke** [comment]
Thanks @revk for the proposal. These current events indeed illustrates the complexity of agreeing on time. This situation is already covered by the "Political Time" section of the [The Long, Painful History of Time](http://naggum.no/lugm-time.html) article from 1999, which is already referenced in the awesome list.
