### ISSUE TITLE
Falsehoods About Language

### ISSUE THREAD

**Issue by benhamill** [kdeldycke/awesome-falsehood#16]
I wrote an article that I think is a good candidate for inclusion (inspired by this repo and an episode of >Code): http://garbled.benhamill.com/2017/04/18/falsehoods-programmers-believe-about-language/

I'm not sure if it would need a new section or if someone wants to make a case for it fitting into one of the existing sections. Wanted to get guidance on that before I made a PR.

**Comment by kdeldycke** [comment]
Looks like a good inclusion to me.

A new section seems appropriate. As for the name, `Language` looks OK, maybe `Internationalization`. Do you have any preference?

While you're at it, you should move there the `i18n Testing Data` link from the `Software Engineering` section.

I'm waiting for your PR! :)

**Comment by kdeldycke** [comment]
Oh, and let's make a deal: would you be OK to link to this repository from your article? :innocent:

**Comment by tompazourek** [comment]
@kdeldycke Hi Kevin, what's your stance on YouTube videos being included in the list?

I've read Ben's article, which is great btw, and it reminded me of an older video that Tom Scott did for Computerfile that sort of touches similar topics: [Internationalis(z)ing Code](https://www.youtube.com/watch?v=0j74jcxSunY). He also did a [similar kind of video about timezones](https://www.youtube.com/watch?v=-5wpm-gesOY&t=1s).

**Comment by kdeldycke** [comment]
Thanks @tompazourek for the proposal. I'm not against them at all.

This repository hasn't entered yet a phase of aggressive curation, so feel free to create a PR! :)

**Comment by kdeldycke** [comment]
Issue has been addressed by #17 and #18.

**Comment by tompazourek** [comment]
Actually, it hasn't been addressed yet. I didn't add link to Ben's article above. But I suppose I can add it later as well as another PR...

**Comment by kdeldycke** [comment]
@tompazourek Feel free to open a new PR. I'm re-opening this issue in the mean time.
