### ISSUE TITLE
Falsehoods Programmers Believe About HTML

### ISSUE THREAD

**Issue by aartaka** [kdeldycke/awesome-falsehood#180]
### URL of the article or project

https://www.aartaka.me.eu.org/falsehoods-html

### Motivation

HTML is the basis for all the web, including the interfaces we're communicating with in this issue. But it's still surrounded with some misconceptions worth refuting. So here's one with falsehoods about HTML.

I'm opening an issue because there seems to be no obvious category for this link in the README. I trust you judgement on where it belongs.

### Affiliation

- [X] I am the author of the article or project
- [ ] I am working for/with the company which is publishing the article or project
- [ ] I'm just a rando who stumbled upon this via social networks

### Self checks

- [X] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/code-of-conduct.md)

- [X] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/contributing.md)

- [X] I have checked there is no other [Issues](https://github.com/kdeldycke/awesome-falsehood/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-falsehood/pulls) covering the same topic to open

**Comment by kdeldycke** [comment]
That's a good one! Just pushed it upstream in https://github.com/kdeldycke/awesome-falsehood/commit/52ea84f39ec525baa7b5e4bfcc211190d0c917aa
