### ISSUE TITLE
Falsehoods that aren't explicitly factual or related to programming

### ISSUE THREAD

**Issue by treemonkey999** [kdeldycke/awesome-falsehood#20]
Falsehoods Programmers Believe About "Women In Tech" seems incredibly combative and toxic. It's also not really factual and doesn't fit in with the other examples that are really related to programming falsehoods, like how to validate emails. It's more like an angry agenda piece.

Same for "Falsehoods about Gender". This seems like a political agenda piece that is not related to programming.

Why not keep this list strictly related to things that are actually about programming and not controversial? Like i18n or build systems, etc. It's distracting from the rest of the list, and takes away credibility.

**Comment by kdeldycke** [comment]
Already discussed in #4.
