### ISSUE TITLE
consider Chinese translation

### ISSUE THREAD

**Issue by gongxuanzhang** [kdeldycke/awesome-falsehood#208]
Whether to consider Chinese translation. I want to contribute to that

**Comment by kdeldycke** [comment]
I'll be happy to have a Chinese translated version! I already have this for Awesome IAM: https://github.com/kdeldycke/awesome-iam/blob/main/readme.zh.md

So if you want to contribute you can propose a PR. You can start by duplicating the `readme.md` file and name it `readme.zh.md`, then translate as much as you can. You can take Awesome IAM as a guide.

**Comment by gongxuanzhang** [comment]
@kdeldycke  I noticed there is a link about contributing in the README. Should we also have a Chinese version of the contribution guide and add a language switch button in the README?

**Comment by kdeldycke** [comment]
I was planning to add the badges later on this week but feel free to do it: look at how I've done it on Awesome IAM.

As for thé contribution guide, I trust you judgement. If you think it can help improve contributions in Chinese, I'll be happy to merge it to the project! :)

**Comment by gongxuanzhang** [comment]
Thanks for your answer. I will do it :)

**Comment by gongxuanzhang** [comment]
It's done

**Comment by kdeldycke** [comment]
Thanks a lot @gongxuanzhang for your work! 🥳
