### ISSUE TITLE
People born sequentially may have out of order birth times

### ISSUE THREAD

**Issue by kurtseifried** [kdeldycke/awesome-falsehood#23]
I'm not sure how to put this but:

If you give birth to twins right around the time daylight savings kicks in you can end up with the first born twin being (according to records) younger than the second born twin.

http://people.com/human-interest/second-born-twin-is-actually-older-than-brother-thanks-to-daylight-savings-time-twist/

Maybe we need a set of falsehoods programmers believe about birth records (like assuming they exist...) and other forms of government records (in past times hospitals have burnt down, taking all the paper records of births with them, leaving a number of people in a difficult state to prove that they exist officially).

**Comment by mjrider** [comment]
sounds more like a 'timezones and daylight saving are hard to understand' problem, then a 'falsehood'
causes:
* the human reading the information is buggy
* the records are missing a DST/timezone identifier

**Comment by kdeldycke** [comment]
I agree with @mjrider, that's typical consequences of timezone and DST falsehoods.

But thanks @kurtseifried for that really funny case! :)

**Comment by kdeldycke** [comment]
OTOH if you want to add that link to the timezone section, feel free to create a PR! :)

**Comment by yakatz** [comment]
Similarly, on the Jewish calendar, a leap year adds a whole month (to keep the solar and lunar calendars in sync). This leaves a whole month of older-younger birthday issues during non-leap-years when all dates from the leap-month move to the same day of the next month.
