### ISSUE TITLE
Request: replicate lists in this repo if their license allows

### ISSUE THREAD

**Issue by sparr** [kdeldycke/awesome-falsehood#24]
This would make the repository more future-proof than just having a list of links to other sites that eventually go offline.

**Comment by kdeldycke** [comment]
Thanks @sparr for the proposal!

It's a huge endeavour that requires to check all the licence under which the source articles were published, as we can't host content in this repository that is not under a Creative Commons CC0 (per [*Awesome*'s requirements](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license)). This also imply we'll need to ask the permission of original authors to re-licence their work.

That being said, it's a good idea to host falsehoods list directly in this repository, if there is no licensing conflicts. Just send a pull request with the appropriate documentation and I'll be happy to review it! :)

In the mean time, we can easily replace a broken link by its snapshot from `archive.org`.
