### ISSUE TITLE
RFC: Fun story I read about a man named <MAGIC_CONSTANT>...

### ISSUE THREAD

**Issue by mar77i** [kdeldycke/awesome-falsehood#3]
I'd like to discuss the inclusion of this article.

https://www.wired.com/2015/11/null/

**Comment by kdeldycke** [comment]
Thanks @mar77i for the contribution! This article really is a great real-life example of how falsehoods programmers believe in may have an impact on someone's life.

Added it in c34509a2c501d86e29327fc9f1c2740650d4baa0.
