### ISSUE TITLE
Falsehoods about text

### ISSUE THREAD

**Issue by Manishearth** [kdeldycke/awesome-falsehood#34]
https://manishearth.github.io/blog/2017/01/14/stop-ascribing-meaning-to-unicode-code-points/

It's not structured as a "falsehoods" article but it's talking about a major one that's a pain when folks who use a language with a script other than Latin try to use software.

https://manishearth.github.io/blog/2017/01/15/breaking-our-latin-1-assumptions/ is another similar one, structured more like a falsehoods article.

**Comment by kdeldycke** [comment]
Thanks @Manishearth for the contribution and sorry for the delay. Your links have been added in https://github.com/kdeldycke/awesome-falsehood/commit/a21352d0d828aa6f13da1e2c03e59798428b88c7 .
