### ISSUE TITLE
Gay Marriage: The Database Engineering Perspective - Article Unavailable

### ISSUE THREAD

**Issue by LaurelineSwissBorg** [kdeldycke/awesome-falsehood#42]
The article *Gay Marriage: The Database Engineering Perspective* at https://qntm.org/gay has become unavailable. The author is rewriting the article and has taken down the previous version.

An archived version is available at: https://web.archive.org/web/20170914014648/https://qntm.org/gay

**Comment by kdeldycke** [comment]
Thanks @LaurelineSwissBorg for the contribution and sorry for the delay! I just fixed the link in https://github.com/kdeldycke/awesome-falsehood/commit/229936626196ecf6edf42f66deee621ae9fd30d6 .
