### ISSUE TITLE
Can someone add "Falsehoods Programmers Believe About Search"?

### ISSUE THREAD

**Issue by sonergonul** [kdeldycke/awesome-falsehood#44]
[Falsehoods Programmers Believe About Search](https://opensourceconnections.com/blog/2019/05/29/falsehoods-programmers-believe-about-search/) is a great article and it should be add to the list. Somehow I couldn't submit a pull request :\

**Comment by anarchivist** [comment]
Great minds think alike! 😸

**Comment by kdeldycke** [comment]
Done! :)
