### ISSUE TITLE
I'd love to see falsehoods about videogame design and development. 

### ISSUE THREAD

**Issue by brainard52** [kdeldycke/awesome-falsehood#54]
I don't have the ability to contribute in a meaningful way. I'd still love to see something regarding videogames since it would be a good resource for new developers.

**Comment by kdeldycke** [comment]
No resource about falsehoods in video game had magically appeared on the web since then. Closing this issue.

**Comment by kdeldycke** [comment]
With patience, magic happens. Just inaugurated a new section for video games: https://github.com/kdeldycke/awesome-falsehood#video-games 😁
