### ISSUE TITLE
IBAN description text misleading

### ISSUE THREAD

**Issue by pixelyo** [kdeldycke/awesome-falsehood#57]
> Falsehoods About IBANs - International Bank Account Numbers are not immune to mistakes.

In the linked article I cannot find the claim that IBANs are not immune to mistakes. The closes I found was that IBANs don't help in "find the source of an input problem".

**Comment by kdeldycke** [comment]
I guess I added that generic description to keep things simple. So you have an idea of a more specific description?

**Comment by pixelyo** [comment]
maybe something like

> International Bank Account Numbers are not international.

or

> International Bank Account Numbers are not used in every country.

**Comment by kdeldycke** [comment]
Ahaha I love the first one! Just pushed you proposal in https://github.com/kdeldycke/awesome-falsehood/commit/47d793f8ba781c7ca47d1d00980487423ef2103a .
