### ISSUE TITLE
Falsehoods programmers believe about benchmarking

### ISSUE THREAD

**Issue by stylpe** [kdeldycke/awesome-falsehood#87]
#### Preliminary checks

* [X] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/code-of-conduct.md)
* [ ] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/contributing.md)
* [X] I have checked there is not other [Issues](https://github.com/kdeldycke/awesome-falsehood/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-falsehood/pulls) covering the same topic to open

#### Summary

Benchmarks are notorious for being hard to get right, with mistakes and oversights on so many levels, and should be a prime candidate for a Falsehoods list.

Sorry for not bringing any links, this is a bit of a drive-by idea. Google gives more results for "myths" and "pitfalls" but they're mostly blog post, I couldn't find any decently sized lists on the first page.

**Comment by kdeldycke** [comment]
Thanks @stylpe for the proposal. And I agree, benchmarking is hard and full of falsehoods. See for instance how some micro-benchmarking are abused to influence the perception of performances.

In the absence of material articles on the topic, I'll close this issue but will reference it in the future if something related to benchmarking appears on the web.
